JFLAGS = -d ./bin
JC = javac
FOLDER = ./src/

run: 
	$(JC) $(JFLAGS) $(FOLDER)Main.java $(FOLDER)GerenciadorDeSalas.java \
		$(FOLDER)MarcadorDeReuniao.java $(FOLDER)Menu.java $(FOLDER)Reserva.java \
		$(FOLDER)Sala.java $(FOLDER)InterfaceSala.java $(FOLDER)InterfaceReserva.java \
		$(FOLDER)InterfaceGerenciadorDeSalas.java $(FOLDER)InterfaceMarcadorDeReuniao.java

